In [1]:
import numpy as np

import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

plt.rcParams["figure.figsize"] = 10, 8

In [7]:
RMAX   = 15
ZMAX   = 0.3
STEP   = 5e-3
NPART  = int(1)
NSPLIT = int(1e4)

RMAX2 = RMAX**2

In [11]:
def coordinates():
    while True:
        for i in np.random.uniform(-STEP, STEP, size=(int(1e6), 3)):
            yield i

def r2_z(pos):
    return pos[0]**2 + pos[1]**2, pos[2]


def propagate(x0, y0, z0, weight, rsplit=np.inf):
    pos     = np.array([x0, y0, z0], dtype=np.float)
    rsplit2 = rsplit**2
    for step in coordinates():
        pos += step
        r2, z = r2_z(pos)
        
        if abs(z) >= ZMAX or r2 >= RMAX2:
            return pos, weight
        
        if r2 >= rsplit2:
            for _ in range(NSPLIT):
                for p, w in propagate(*pos, rmax, zmax, weight/NSPLIT, rsplit=1.5*rsplit):
                    return p, w

def simulate_cr(*args, **kwargs):
    return list(propagate(*args, **kwargs))

In [12]:
positions = []
weights   = []
for _ in range(NPART):
    pos, w = zip(*simulate_cr(0, 0, 0, 1))
    positions.extend(pos)
    weights  .extend(weights)

[-0.0046332   0.00389748 -0.00383241] 3.665691408005921e-05 -0.0038324127451663395
[-0.00850756  0.00595421 -0.00195468] 0.00010783115611469206 -0.0019546805051858344
[-0.01144536  0.00938335 -0.00321496] 0.00021904364347303395 -0.0032149638367946634
[-0.00666494  0.00701743 -0.00594976] 9.366570453914284e-05 -0.005949764623597961
[-0.00323264  0.00753494 -0.00921047] 6.722525078144582e-05 -0.009210465579033185
[-0.00596424  0.00663412 -0.01103921] 7.958371372726906e-05 -0.011039205234821537
[-0.00260299  0.00253098 -0.01095055] 1.3181400074427222e-05 -0.010950554664865674
[-0.00361964 -0.00226638 -0.01330763] 1.823828346137318e-05 -0.013307627237232857
[-0.00052814  0.00128596 -0.01739494] 1.9326266851367052e-06 -0.017394936207601255
[ 0.00058462  0.0051077  -0.01647871] 2.643033550307429e-05 -0.016478710932732094
[-0.0008328   0.00143777 -0.01893917] 2.760747893053926e-06 -0.01893916521499824
[-0.00352983 -0.0029587  -0.01608308] 2.1213604275812864e-05 -0.01608307858717674
[-0.008005

[-0.01772666  0.06510946  0.01668726] 0.004553476014741121 0.016687264051242146
[-0.0189119   0.06072433  0.02105833] 0.0040451041456128186 0.021058333322767468
[-0.01796902  0.05837568  0.01997484] 0.00373060595840267 0.0199748369609675
[-0.02056632  0.06279233  0.0214599 ] 0.004365850784910266 0.021459899869465535
[-0.02495096  0.06252401  0.01788713] 0.004531802601212744 0.017887129301746966
[-0.02986585  0.06241236  0.01768237] 0.004787272003789234 0.017682371676309778
[-0.02982941  0.05941641  0.01625756] 0.004420104203111518 0.016257557749028494
[-0.03352542  0.05527451  0.01275894] 0.00417922559450711 0.01275893901574977
[-0.03546294  0.05816138  0.0092873 ] 0.004640366225565095 0.009287295219092117
[-0.03949254  0.05492068  0.00549201] 0.004575941374755253 0.00549201216542316
[-0.0411666   0.05399741  0.00530957] 0.004610409552342278 0.0053095677913077175
[-0.03634808  0.05625813  0.00162484] 0.0044861598487702875 0.001624840594332157
[-0.03992601  0.05705929 -0.00189182] 0.004

[-0.08329161  0.07998501  0.12369081] 0.013335093702561078 0.12369081306031804
[-0.0857943   0.08315506  0.1259856 ] 0.014275426595318212 0.12598560466193387
[-0.08081238  0.08443092  0.12966325] 0.013659221899638833 0.1296632479125079
[-0.07611206  0.08295619  0.13447373] 0.012674774579191275 0.13447372722248493
[-0.07553078  0.08418555  0.1351757 ] 0.012792105841269781 0.13517569688798076
[-0.07394654  0.08799696  0.13803768] 0.013211555524563488 0.1380376829101773
[-0.0747685   0.09297495  0.14093939] 0.014234669474578377 0.14093938547882803
[-0.07059957  0.09291735  0.14208804] 0.013617933245009147 0.14208803859114552
[-0.07103342  0.08970185  0.14549029] 0.013092169114591424 0.14549028847205506
[-0.07366192  0.08626747  0.15044872] 0.012868154364479353 0.15044872272266233
[-0.07157372  0.08760402  0.14642285] 0.01279726210607899 0.1464228522304718
[-0.06968056  0.08591711  0.14410961] 0.012237129349254465 0.14410960887780155
[-0.07176549  0.08652963  0.14014124] 0.0126376637776406

[-0.11641719  0.17718759  0.11365982] 0.04494840390527595 0.11365981718938253
[-0.11373028  0.17833744  0.108989  ] 0.04473881776104753 0.10898900465035831
[-0.11347322  0.1733725   0.11163994] 0.04293419420551551 0.11163993978312713
[-0.10893236  0.1760802   0.11461067] 0.04287049473963299 0.11461067009000998
[-0.10497095  0.17568445  0.11412214] 0.04188392691977253 0.11412214052247295
[-0.10465137  0.17248985  0.11171163] 0.04070465721643026 0.11171163332894675
[-0.10909934  0.17724029  0.11512012] 0.04331678770146304 0.11512012431703003
[-0.10433925  0.17759068  0.11157148] 0.042425128923290485 0.11157148457657311
[-0.09947919  0.18102796  0.11040279] 0.042667228830320696 0.1104027918714108
[-0.10211765  0.18495514  0.11529046] 0.044636416602314814 0.1152904639652538
[-0.10466986  0.1880181   0.11895356] 0.046306585586193716 0.11895355975966905
[-0.10615062  0.18868966  0.11595886] 0.0468717416342775 0.11595885605169821
[-0.10369998  0.19278012  0.11530832] 0.047917859213534406 0.11

[-0.11120117  0.28158502 -0.00178797] 0.09165582339535193 -0.001787972055007555
[-0.11075963  0.28507865 -0.00239095] 0.09353753052783177 -0.0023909500921251137
[-0.11180418  0.28290709 -0.00368936] 0.0925365961620783 -0.003689362105359012
[-0.10689274  0.28614514 -0.00381681] 0.09330509892609685 -0.0038168053018011565
[-0.11140456  0.28147203 -0.00299555] 0.09163748005661398 -0.0029955504735701367
[-0.11557845  0.27862336 -0.00525756] 0.09098935335796499 -0.005257557278076249
[-0.11939777  0.27754625 -0.00478272] 0.09128774842642773 -0.004782723943496918
[-0.11505061  0.27338451 -0.00427825] 0.08797573355293209 -0.004278250612015421
[-0.11986251  0.27271317  0.00065666] 0.08873949450971547 0.0006566570504343196
[-1.18990062e-01  2.75221708e-01  1.70169234e-04] 0.08990562357612407 0.00017016923355820182
[-0.11674329  0.27522022 -0.00327483] 0.0893751633958258 -0.00327483418716525
[-0.11440999  0.27214766 -0.00389704] 0.08715399756732864 -0.003897039380232624
[-0.11751979  0.27428408  0

[-0.08749987  0.37466363 -0.02441811] 0.14802906573654478 -0.024418114045333707
[-0.08609589  0.37383784 -0.02059138] 0.14716723372224005 -0.020591375947415478
[-0.08560311  0.37719583 -0.02083386] 0.14960458866111168 -0.02083385971894696
[-0.08843129  0.37830543 -0.02441132] 0.1509350913469941 -0.02441131954387786
[-0.08588197  0.37545581 -0.02375273] 0.1483427793182749 -0.02375273128545701
[-0.08522682  0.37642944 -0.02514477] 0.14896273329254248 -0.025144770920235524
[-0.08680243  0.37915496 -0.02414071] 0.15129314773948369 -0.02414070684026842
[-0.08808382  0.38041045 -0.02545005] 0.15247086782453753 -0.025450049712294694
[-0.08310525  0.38455632 -0.02899918] 0.1547900438066977 -0.028999179909700305
[-0.08295541  0.38616906 -0.0249977 ] 0.15600814061256107 -0.02499769722167523
[-0.08011795  0.38970883 -0.02278509] 0.15829185968827886 -0.022785091579156095
[-0.08228185  0.38675979 -0.01846078] 0.15635343839117677 -0.01846078109519203
[-0.08289387  0.39106534 -0.02181879] 0.159803491

[-0.06284408  0.32826937  0.00148612] 0.11171015755170711 0.00148612101271653
[-0.05872483  0.32693413 -0.00082855] 0.11033453261450499 -0.0008285465535093533
[-0.06156514  0.32691115 -0.00429237] 0.11066116493043704 -0.004292370399128591
[-0.06045099  0.32512356 -0.00693836] 0.10935965041524187 -0.006938356363622266
[-0.064873    0.32863872 -0.01025762] 0.11221191174649685 -0.010257618208240137
[-0.06177746  0.32518205 -0.01198585] 0.10955982280024018 -0.01198585221357647
[-0.06582336  0.32901002 -0.00871006] 0.11258030929407399 -0.008710061120586858
[-0.06570197  0.32992036 -0.00953687] 0.11316419330063233 -0.00953686685005134
[-0.06099913  0.33083836 -0.00787389] 0.1131749114222532 -0.007873891718808063
[-0.05926785  0.33552219 -0.01051439] 0.11608782095777728 -0.010514393019551557
[-0.05534179  0.33092547 -0.01352785] 0.11257437998798699 -0.013527846088800356
[-0.05603076  0.33120678 -0.01371273] 0.11283737642283509 -0.013712729888020764
[-0.0603539   0.33111833 -0.01049411] 0.1132

[-0.19976911  0.30544513 -0.00290354] 0.13320442313761008 -0.002903541111711653
[-0.19960635  0.30141307 -0.00109201] 0.13069253254644533 -0.0010920115970057508
[-0.20235608  0.30382265  0.00349613] 0.13325618488046947 0.003496131218938411
[-0.19925268  0.30413148 -0.0003566 ] 0.1321975860200525 -0.00035660492203601346
[-0.19809232  0.30867635 -0.00066783] 0.1345216595663861 -0.0006678313880659793
[-0.20012116  0.31296728 -0.00043091] 0.13799700185794989 -0.0004309090858282084
[-0.19607242  0.30979196  0.00450731] 0.13441545456927195 0.0045073148661667894
[-0.19156657  0.31047307 -0.00040154] 0.13309127646541888 -0.00040153876496838194
[-0.19055089  0.31337655  0.00420355] 0.13451450491864797 0.004203553995829679
[-0.1858248   0.31352707  0.00500272] 0.13283007707231975 0.005002722438855114
[-0.18572592  0.30958043  0.00878594] 0.13033415967035233 0.008785937290252961
[-0.18226975  0.30867493  0.01207711] 0.12850247480717034 0.01207710813948202
[-0.18198152  0.30779197  0.01540898] 0.1

[-0.19617284  0.3338826   0.089306  ] 0.1499613761028076 0.08930600051534943
[-0.19597487  0.33185244  0.09334527] 0.14853218823906653 0.09334527230386273
[-0.19607074  0.33403181  0.08912375] 0.1500209868908366 0.08912375268052464
[-0.19681375  0.33395113  0.09113205] 0.15025900912682955 0.09113204574725556
[-0.19965102  0.33207128  0.08847471] 0.1501318635724345 0.08847470688709708
[-0.20134586  0.33162563  0.0847217 ] 0.15051571592752333 0.08472169998438898
[-0.20285528  0.32955649  0.08082936] 0.14975774498152114 0.08082935506563536
[-0.20116386  0.32891832  0.07832962] 0.14865415829548057 0.07832962215912638
[-0.20239093  0.3283736   0.07954008] 0.14879130821321454 0.07954008258398548
[-0.20684818  0.32590392  0.07744462] 0.14899953841359165 0.07744462334135696
[-0.20189446  0.32694495  0.07587625] 0.14765437577070317 0.07587624900193193
[-0.20075846  0.33008496  0.07887869] 0.14926004185527958 0.07887868943505551
[-0.20473562  0.32816737  0.08054674] 0.14961049623750347 0.0805467

[-0.21465375  0.37583227  0.14768001] 0.1873261303435111 0.1476800107875223
[-0.21477469  0.38041958  0.14968912] 0.19084722494146847 0.1496891187630219
[-0.21236411  0.37810491  0.14816358] 0.18806183964173534 0.14816358250796927
[-0.21364743  0.38002782  0.14486072] 0.19006636725048753 0.14486072461765306
[-0.21420911  0.37646668  0.14928168] 0.18761270943585354 0.1492816822450048
[-0.21496356  0.37599784  0.14904142] 0.1875837096784738 0.14904141923578645
[-0.21595942  0.37781257  0.15188971] 0.18938081221386902 0.15188970598457247
[-0.21096421  0.38129638  0.15476022] 0.18989282620473993 0.15476021775106188
[-0.20625831  0.38377347  0.15787196] 0.18982456566087932 0.15787196477081858
[-0.20206455  0.38364     0.15450221] 0.18800973104336735 0.1545022116050744
[-0.20412506  0.37871646  0.15775018] 0.18509319759744747 0.15775018047072542
[-0.20534858  0.38125478  0.15898041] 0.18752325206167064 0.1589804094459773
[-0.20494982  0.37708688  0.16144754] 0.18419894850888963 0.16144754284

[-0.17724923  0.40613675  0.08640216] 0.19636435380627115 0.08640215588586471
[-0.1753253   0.40810597  0.08228081] 0.19728944086992994 0.0822808081467804
[-0.17705473  0.41135919  0.07791791] 0.20056475839053567 0.07791791024278456
[-0.17471133  0.41068574  0.07571049] 0.19918682057491888 0.07571049240098622
[-0.17816436  0.41220527  0.07961001] 0.2016557267213061 0.07961000954201243
[-0.17790994  0.40775246  0.08038484] 0.1979140106538152 0.08038483551399955
[-0.17695703  0.41036589  0.07811432] 0.19971395496705488 0.07811432496276752
[-0.17304188  0.40934757  0.07329018] 0.1975089229378567 0.07329017689615569
[-0.17293971  0.40994961  0.07611137] 0.19796682697877163 0.07611137453226631
[-0.1766736   0.41370463  0.07942599] 0.20236508239827175 0.07942599280525339
[-0.17372404  0.41575036  0.07678414] 0.20302840270545555 0.07678413814883969
[-0.17006408  0.41132962  0.07844221] 0.19811385028922618 0.07844220593571542
[-0.1747545   0.41533392  0.07789843] 0.20304139894715575 0.07789842

[-0.13542199  0.40452636  0.04283332] 0.18198069161489688 0.042833320105510414
[-0.13319346  0.40700082  0.04132542] 0.1833901644323358 0.041325415680526445
[-0.13649162  0.4110698   0.04052035] 0.18760834545716581 0.04052035087932114
[-0.14004508  0.41283255  0.03764802] 0.19004333885340197 0.03764801709671615
[-0.1392104   0.41248177  0.03710439] 0.18952074224474752 0.03710438517932396
[-0.13997187  0.41529239  0.03533133] 0.19205989120798228 0.03533132869331837
[-0.14324576  0.41724159  0.0306338 ] 0.19460989055199518 0.030633796303233124
[-0.14352139  0.41968078  0.0332241 ] 0.19673034463667224 0.03322409958808201
[-0.14293692  0.42260018  0.03189063] 0.19902187163232887 0.03189062887443822
[-0.14423981  0.42057554  0.0356284 ] 0.19768890917368848 0.03562839568920701
[-0.14331884  0.41576995  0.03556989] 0.19340494055552965 0.03556989492708432
[-0.14194546  0.42037711  0.03815753] 0.19686542473557628 0.038157534501880745
[-0.14326744  0.41718027  0.03545511] 0.19456493897765942 0.0

[-0.12914439  0.4721412   0.05254193] 0.23959559191854707 0.05254192546716021
[-0.1311396   0.4707377   0.05247833] 0.2387915739035022 0.05247832592771479
[-0.13092059  0.46731576  0.05311812] 0.23552422456192146 0.053118116269008656
[-0.12722541  0.47078188  0.05655665] 0.23782188289437875 0.05655664540592184
[-0.12833854  0.46968297  0.05530715] 0.23707287099992963 0.05530714730125203
[-0.13119127  0.46582603  0.05160007] 0.23420503817271843 0.0516000717319124
[-0.12897987  0.46323995  0.0475833 ] 0.23122705815863034 0.047583299320965645
[-0.13305057  0.46576974  0.0516661 ] 0.23464390791757808 0.05166610322940009
[-0.13407917  0.46494979  0.05514968] 0.23415552700676726 0.05514967996756812
[-0.1307393   0.46191878  0.05411087] 0.23046171977844826 0.054110868939858586
[-0.12816166  0.46469965  0.054096  ] 0.23237117373059976 0.054096003335302685
[-0.12492668  0.4638836   0.05543355] 0.23079466910040722 0.055433548504325025
[-0.12584829  0.46632162  0.05344174] 0.23329364917746126 0.0

[-0.13113252  0.41273332  0.27963707] 0.18754453405754523 0.2796370742695425
[-0.13107778  0.41100006  0.27970249] 0.1861024316435279 0.2797024899416706
[-0.13292941  0.4145643   0.27882717] 0.1895337860258826 0.27882716988295736
[-0.13299942  0.41688715  0.27982684] 0.19148374183770484 0.27982683688987464
[-0.13243922  0.41911507  0.2773484 ] 0.19319759039304404 0.27734839896096275
[-0.1283563   0.42254997  0.27864241] 0.19502382021356193 0.27864241021138986
[-0.12941708  0.42424067  0.28227188] 0.1967289240921908 0.2822718759071025
[-0.12763632  0.42124586  0.27758356] 0.1937391012554994 0.2775835631026608
[-0.13038742  0.42297902  0.28067836] 0.19591212980426218 0.2806783625135676
[-0.12595625  0.4274207   0.28214602] 0.19855343357026403 0.2821460157932725
[-0.12692649  0.42924495  0.28137534] 0.20036155771354341 0.2813753368667402
[-0.1229639   0.43164264  0.28530828] 0.2014354911938561 0.2853082756767291
[-0.11894016  0.43049967  0.28229801] 0.19947673214677403 0.28229801247638436

[-0.07229083  0.37984546  0.30793866] 0.14950853396038902 0.30793865573920703
[-0.0702266   0.3756579   0.31113081] 0.1460506322690414 0.31113080903362106
[-0.07440011  0.37773043  0.30822829] 0.14821565222672764 0.30822828779285316
[-0.07544245  0.37314538  0.31173927] 0.14492904213562557 0.3117392677927443
[-0.07324578  0.37356554  0.30944173] 0.14491615880773065 0.3094417300284701
[-0.07087243  0.37426749  0.30793401] 0.14509905494338918 0.30793400670056525
[-0.0724489   0.37015304  0.31061765] 0.14226211331900523 0.31061764767541583
[-0.0676536   0.37364584  0.31361229] 0.14418822632902167 0.3136122912590061
[-0.07199002  0.37021682  0.31268732] 0.1422430602321676 0.3126873234257326
[-0.07025457  0.3744125   0.31182623] 0.14512042383837537 0.3118262251881717
[-0.06732361  0.37477748  0.30753884] 0.14499063037857662 0.3075388439832435
[-0.07098495  0.37799796  0.30939626] 0.1479213233329069 0.3093962575083341
[-0.07066684  0.38217095  0.30928126] 0.15104843841218896 0.30928126322890

[-0.07883095  0.55051949  0.45289515] 0.3092860259899447 0.45289514948126713
[-0.08232441  0.54815061  0.45456587] 0.3072464026181332 0.4545658655157494
[-0.07933625  0.54565346  0.45156049] 0.3040319377026056 0.45156048733210635
[-0.08156793  0.54884346  0.45364131] 0.30788247472112 0.45364131196752994
[-0.08634926  0.55039565  0.45419926] 0.3103915635306711 0.45419925938036093
[-0.08892355  0.5543862   0.45044217] 0.3152514604196413 0.4504421721538733
[-0.08690757  0.55511725  0.44671475] 0.31570808364469793 0.4467147476901868
[-0.08766051  0.55390456  0.45085181] 0.31449462411838947 0.4508518075658561
[-0.08376591  0.54996056  0.45558685] 0.3094733477594901 0.45558685230779056
[-0.08479633  0.55400153  0.45404846] 0.31410811355608365 0.45404845582602404
[-0.08228558  0.5523129   0.45498529] 0.3118204537156642 0.4549852933970197
[-0.08297631  0.55370233  0.45132266] 0.31347133441364644 0.4513226626629686
[-0.07997924  0.5512474   0.45367859] 0.31027037405243807 0.45367859078849726
[-

[0.00375086 0.51786514 0.44414515] 0.26819837081915615 0.4441451478076776
[5.16345077e-04 5.22766746e-01 4.44639894e-01] 0.2732853374291165 0.4446398935005752
[-1.22178937e-05  5.24856944e-01  4.45705052e-01] 0.2754748117152321 0.44570505205455285
[-0.00117453  0.52216813  0.44974109] 0.2726609376401386 0.4497410871555564
[0.00097584 0.52653377 0.44608855] 0.2772387674042784 0.4460885461416272
[0.00342675 0.52980642 0.45107255] 0.28070658650429525 0.4510725496559797
[0.00119651 0.53420533 0.45539465] 0.2853767704383286 0.45539464591750944
[-4.16148501e-04  5.36297998e-01  4.55473530e-01] 0.2876157156548575 0.4554735297535333
[0.00166666 0.53976158 0.45091998] 0.2913453357538512 0.450919984577242
[0.00455759 0.53943243 0.44758223] 0.2910081163595569 0.4475822346033803
[0.00458274 0.54095824 0.45221995] 0.29265681671834376 0.4522199497760826
[0.00601204 0.53903032 0.44897582] 0.29058983490433715 0.4489758170927782
[0.00912883 0.5424337  0.44907117] 0.29431765879605265 0.4490711661428106


[-0.046562    0.60182996  0.4488014 ] 0.364367319422227 0.4488013950741292
[-0.04479558  0.59897089  0.44977923] 0.3607727720007968 0.4497792307969027
[-0.04480135  0.59485602  0.44510375] 0.35586084932020706 0.4451037518397771
[-0.04489748  0.59645571  0.44513843] 0.35777520063787466 0.44513842853795077
[-0.04893814  0.59670462  0.4466346 ] 0.35845134622718017 0.4466346024995892
[-0.04967856  0.59420058  0.44820698] 0.35554229398521503 0.4482069795460196
[-0.05375801  0.59348135  0.44698003] 0.35511004066413054 0.4469800283001637
[-0.05382548  0.59357871  0.44907295] 0.3552328647249724 0.4490729520961972
[-0.05746543  0.59761049  0.44714875] 0.36044057427326615 0.44714875439877555
[-0.05958467  0.59808976  0.44502525] 0.36126168851000046 0.44502524984613706
[-0.0546061   0.5960563   0.44053391] 0.35826493524395236 0.44053390654174324
[-0.05090958  0.59520957  0.43733127] 0.3568662227477851 0.43733126572901865
[-0.05041405  0.59240321  0.43574991] 0.353483134621844 0.4357499068332199
[

[0.00617803 0.37871164 0.46539063] 0.1434606716713129 0.4653906336087363
[0.00390907 0.37519494 0.46571836] 0.14078652302532763 0.4657183585831524
[0.00236933 0.3730903  0.46356247] 0.1392019840249787 0.4635624747860545
[0.003067   0.36884813 0.46031657] 0.13605834845279352 0.4603165669329694
[0.00130969 0.37177585 0.46223754] 0.13821899800299506 0.462237541197741
[0.00291099 0.37645425 0.46423089] 0.14172627520974834 0.4642308932495293
[0.00656586 0.37499336 0.46186225] 0.14066313264945648 0.4618622462060072
[0.00206687 0.37942513 0.46551909] 0.1439677033431864 0.46551909442240946
[0.00664147 0.37970944 0.46225661] 0.14422336681642614 0.46225660852291933
[0.0062468  0.38467671 0.4575262 ] 0.14801519207782296 0.45752620029846525
[0.01032021 0.3857856  0.45668257] 0.1489370389461754 0.45668257314772953
[0.01253403 0.38890741 0.45994015] 0.1514060736476985 0.4599401504493585
[0.01746695 0.39141649 0.46151712] 0.15351196316337848 0.4615171222759956
[0.01979367 0.39604959 0.4629004 ] 0.157

[0.0221938  0.46834638 0.37983002] 0.21984089534024034 0.37983002097913926
[0.0205061  0.46428121 0.37865989] 0.21597754427676152 0.3786598942494374
[0.01964117 0.46236618 0.38111355] 0.21416825629120603 0.3811135499086176
[0.015097   0.46493124 0.37941115] 0.2163889791174227 0.3794111453729788
[0.0111249  0.46813745 0.38410395] 0.2192764328292225 0.3841039520364865
[0.01394274 0.46712879 0.38220604] 0.21840370365473114 0.3822060365399402
[0.01296082 0.46840838 0.37814841] 0.21957439603066656 0.3781484137424948
[0.01211354 0.46575204 0.37979298] 0.21707169908150659 0.37979298264357897
[0.01676978 0.46123928 0.37714991] 0.21302289616017828 0.3771499069512977
[0.01460932 0.45854194 0.37558745] 0.21047414647114504 0.37558744596235266
[0.01367271 0.4616553  0.37796117] 0.2133125627217959 0.377961166348523
[0.01142231 0.46571592 0.37678541] 0.21702178521469503 0.37678540587940246
[0.01260888 0.4662749  0.37502309] 0.21757126240806604 0.37502309128915046
[0.01077649 0.46985189 0.37252743] 0.

[0.09126302 0.46132199 0.32648477] 0.2211469177053126 0.3264847731751409
[0.08693135 0.46236826 0.32981361] 0.22134146317983877 0.3298136101314395
[0.08642684 0.46670177 0.33078795] 0.22528014406268754 0.3307879470936155
[0.08238867 0.46488535 0.33190647] 0.22290627743283023 0.3319064699812168
[0.08472531 0.46252264 0.33096625] 0.22110556929831304 0.3309662549439879
[0.08625538 0.45859527 0.33376398] 0.21774961144681768 0.33376397556474047
[0.08367186 0.46322357 0.3302014 ] 0.22157705757003943 0.33020140062191583
[0.08304171 0.46462606 0.32921018] 0.22277330197942055 0.32921018013524983
[0.08438909 0.46508867 0.32475349] 0.22342898905183234 0.3247534869364072
[0.08820925 0.46412534 0.31990122] 0.2231932003372031 0.31990122490565315
[0.09207033 0.46046326 0.31783214] 0.2205033593722616 0.3178321446944769
[0.08740596 0.45731393 0.3224543 ] 0.2167758343914107 0.3224543037155055
[0.08993228 0.45776604 0.32478524] 0.21763756367535275 0.324785244274552
[0.08941561 0.4530301  0.32847862] 0.21

[0.01294891 0.51125833 0.31837166] 0.26155275842881864 0.3183716610852514
[0.01464727 0.51050835 0.31614367] 0.2608333214808148 0.31614366783660436
[0.01186277 0.51461779 0.31347576] 0.26497219711586 0.31347576139892575
[0.0093275  0.51358988 0.31402819] 0.263861571548723 0.31402818743261973
[0.00886461 0.51373251 0.31459671] 0.2639996693063688 0.31459670925075967
[0.00850825 0.51725932 0.31257641] 0.2676295960096866 0.31257641405745173
[0.00561419 0.5190112  0.31316455] 0.2694041478465562 0.3131645542005803
[0.00807961 0.52102432 0.31566266] 0.2715316176790207 0.3156626622887628
[0.00724618 0.51766678 0.32018733] 0.2680313992635567 0.3201873322280938
[0.00461509 0.5203421  0.31715095] 0.2707772045674448 0.3171509534597926
[0.00055193 0.52238635 0.31256548] 0.272887807946488 0.31256547967311765
[0.00388667 0.52242306 0.31065763] 0.27294095614722486 0.31065763429209564
[0.00356132 0.51930283 0.30812661] 0.26968810949624195 0.30812660959176774
[0.00245701 0.52027174 0.30586368] 0.2706887

[0.00624996 0.51911399 0.32322872] 0.26951839636559 0.323228722394033
[0.00852708 0.52073218 0.318964  ] 0.27123471508628455 0.3189639983200185
[0.00816508 0.51876957 0.32142048] 0.2691885390036193 0.32142048096242476
[0.00704887 0.52271338 0.31656553] 0.27327896797815787 0.31656553240664165
[0.00986891 0.52397765 0.31386025] 0.2746499715657894 0.3138602528334634
[0.01236142 0.52531879 0.31801281] 0.27611263203613096 0.3180128112444323
[0.01603174 0.52786166 0.31792443] 0.2788949528512855 0.3179244327777421
[0.0155877  0.52936991 0.31936797] 0.2804754811544548 0.31936797062017475
[0.01527358 0.53282962 0.3166003 ] 0.2841406821393187 0.31660029995471606
[0.01783102 0.5309873  0.31184393] 0.2822654571191753 0.31184392720338777
[0.01723895 0.52920245 0.30783003] 0.2803524098081277 0.30783003396827663
[0.02009919 0.53086646 0.3092315 ] 0.2822231716925775 0.3092315000034317
[0.01743615 0.53380736 0.31074855] 0.2852543143227543 0.3107485536839206
[0.02036438 0.53419728 0.30776816] 0.28578144

[0.05714565 0.62280848 0.30843552] 0.39115603378026464 0.3084355169388558
[0.05703847 0.6232193  0.30989694] 0.3916556791610806 0.309896938994453
[0.05584076 0.62534034 0.31061865] 0.39416873512443135 0.31061864845334886
[0.0520287  0.62830891 0.30755844] 0.3974790751093345 0.3075584415660037
[0.05113076 0.6266604  0.30417309] 0.3953176168617411 0.30417308540338805
[0.05506601 0.62541133 0.30008685] 0.39417159347972414 0.3000868465934373
[0.05023429 0.62392978 0.29900352] 0.39181185320492273 0.29900351996504015
[0.04722045 0.62465163 0.29869297] 0.3924194298351753 0.29869297376550585
[0.05044187 0.61979997 0.29578439] 0.38669637950344127 0.29578439033817505
[0.05097366 0.62291115 0.29802179] 0.3906166203692675 0.29802179128924144
[0.05256338 0.61810996 0.30287598] 0.384822834367257 0.3028759778486246
[0.05686309 0.61788384 0.30653899] 0.3850138476763741 0.3065389906856246
[0.06121323 0.62125289 0.30757667] 0.3897022071918739 0.3075766724496019
[0.0593797  0.62404261 0.30936368] 0.39295

[0.00994124 0.6914078  0.40149467] 0.47814356982238143 0.40149466744896156
[0.00631752 0.69077017 0.40365781] 0.47720334141928095 0.40365780967642
[0.00338103 0.68680989 0.40546183] 0.4717192622554239 0.40546182603206943
[0.00620462 0.68847151 0.40134087] 0.4740315235637347 0.4013408746260181
[0.00179193 0.68672881 0.40015739] 0.47159966985224655 0.40015738672546813
[0.00507478 0.69123657 0.40314377] 0.47783374573446746 0.4031437687942757
[0.0012163  0.69177729 0.40668371] 0.4785572935095131 0.4066837079584681
[-0.00111874  0.68968623  0.40377197] 0.4756683470088254 0.4037719686071459
[0.00075837 0.68611015 0.39976624] 0.47074770735213456 0.3997662387263789
[0.003759   0.68925323 0.40091159] 0.4750841394434911 0.400911591024201
[0.00868594 0.69075858 0.4020532 ] 0.47722285557298 0.40205320429886365
[0.00699625 0.68881982 0.39873615] 0.474521692070921 0.3987361455641474
[0.00214974 0.68865669 0.3969281 ] 0.474252657425601 0.3969281007873189
[0.00186741 0.69183767 0.40044423] 0.478642842

[0.05289426 0.75176285 0.36107926] 0.5679451902293178 0.36107926258614187
[0.05518471 0.75263689 0.35881579] 0.5695076346725219 0.3588157923567435
[0.05134816 0.74913413 0.35874892] 0.5638385738673751 0.3587489161229505
[0.05461416 0.75015896 0.3545841 ] 0.5657211753277067 0.3545841024888175
[0.05509278 0.7532516  0.35547372] 0.5704231848814234 0.35547371859974974
[0.05031699 0.7569906  0.35193497] 0.5755665656021001 0.35193496965564763
[0.04978049 0.75540471 0.35084631] 0.5731143720184518 0.35084631462291044
[0.04590424 0.75915501 0.35067587] 0.57842352378505 0.3506758712894149
[0.04304125 0.75781506 0.34609749] 0.5761362169602355 0.3460974948116254
[0.04010433 0.75928596 0.34948334] 0.578123531615919 0.34948333941666976
[0.04243698 0.7627234  0.3452065 ] 0.5835478772050092 0.3452064974531047
[0.04248375 0.76217689 0.34537156] 0.5827184823502707 0.3453715566744429
[0.04077356 0.76389566 0.34971346] 0.5851990696813408 0.3497134620068689
[0.03890095 0.75893307 0.35009562] 0.577492694794

[0.00891069 0.81216321 0.32349476] 0.65968847715433 0.32349475669308314
[0.00996555 0.80875969 0.32475279] 0.6541915536905514 0.32475278793765466
[0.00724183 0.81214087 0.329672  ] 0.6596252445590326 0.329672003038546
[0.01134567 0.81088959 0.32673034] 0.6576706515393975 0.3267303413331347
[0.00729613 0.80909115 0.326254  ] 0.6546817172429985 0.32625399574224395
[0.00752487 0.80491678 0.32385385] 0.6479476440742744 0.32385384889407925
[0.00642567 0.80467839 0.32586104] 0.647548601415737 0.3258610446103675
[0.01110254 0.80895098 0.32793427] 0.6545249537130059 0.3279342690455743
[0.00675207 0.80444801 0.32928257] 0.6471821953664887 0.32928256864371935
[0.00368474 0.80289456 0.33342968] 0.6446532448439279 0.3334296803926378
[0.00752149 0.80727415 0.33236811] 0.6517481236960294 0.332368113165903
[0.01180059 0.80997118 0.32974455] 0.6561925583900714 0.3297445535011089
[0.01479963 0.81268505 0.33436516] 0.6606760256148063 0.33436516276203704
[0.01694447 0.81580275 0.33927705] 0.6658212495431

[0.0029072  0.98072162 0.31688038] 0.9618233451322629 0.31688038365084936
[0.00188535 0.97588357 0.31509919] 0.9523523018145157 0.3150991885321349
[4.80604822e-04 9.71477221e-01 3.16440276e-01] 0.9437682213934884 0.31644027634441835
[-7.56244940e-04  9.69059595e-01  3.20856844e-01] 0.9390770700836559 0.3208568438026805
[8.48808290e-04 9.66376491e-01 3.16896824e-01] 0.9338842427336823 0.3168968244402963
[5.57540410e-04 9.71309033e-01 3.14766519e-01] 0.9434415476799042 0.3147665192443333
[-0.00329157  0.96711889  0.31590112] 0.9353297789158249 0.31590112441427953
[-0.00794383  0.96587737  0.31155986] 0.932982197099442 0.31155985609968956
[-0.00814601  0.96335939  0.31275223] 0.9281276792627725 0.31275222569626027
[-0.01077733  0.96319264  0.30805461] 0.9278562124493106 0.3080546079725669
[-0.01156855  0.95913257  0.30917992] 0.9200691226122134 0.30917992481950063
[-0.00702622  0.95422467  0.30897871] 0.9105940907671592 0.3089787068734972
[-0.01175885  0.95325534  0.31134147] 0.9088340221

[0.00670019 0.96158779 0.30044957] 0.9246959770390603 0.3004495713828211
[0.00309338 0.96492287 0.29820866] 0.9310857120971242 0.29820866352757036
[0.00587843 0.96366197 0.29498104] 0.9286789478404035 0.29498103678309784
[0.00452829 0.96644437 0.29743918] 0.934035222649273 0.2974391767444532
[0.00617736 0.96506286 0.29831164] 0.9313844881510597 0.2983116415483787
[0.009796   0.96898708 0.29378556] 0.9390319214010067 0.2937855626386706
[0.00720634 0.97025304 0.29249576] 0.9414428869356795 0.29249576490712903
[0.00346568 0.96964499 0.29626843] 0.9402234137163882 0.29626843296060346
[0.00203012 0.97265463 0.29724304] 0.9460611568490781 0.2972430435881061
[0.00571251 0.97540684 0.30100598] 0.9514511400915973 0.30100598308068677
[0.00225944 0.9790709  0.30504505] 0.958584936265175 0.3050450525935972
[0.00248593 0.97597748 0.30186503] 0.9525382160598401 0.30186503064319276
[-0.00143022  0.97469914  0.30588961] 0.9500404518433376 0.30588960919126135
[-0.00319572  0.97427562  0.31035448] 0.949

[0.00714972 0.91956047 0.36620479] 0.8456425690050688 0.3662047910831076
[0.00509643 0.91537099 0.37086006] 0.837930024028825 0.3708600635839714
[8.73395637e-04 9.10633516e-01 3.68900845e-01] 0.8292541626391758 0.36890084492278913
[-0.00359657  0.91167651  0.37185106] 0.8311669924528337 0.3718510638415184
[-0.00281904  0.91044504  0.37515782] 0.8289181171719443 0.3751578240455109
[-0.00689001  0.90635396  0.37027504] 0.8215249731531821 0.3702750353733479
[-0.0054421   0.91086245  0.36652992] 0.8297000262402097 0.36652991663951706
[-0.00333594  0.91267489  0.36313212] 0.832986589307487 0.3631321179155009
[-0.00319754  0.91175295  0.36315633] 0.8313036599856193 0.3631563254904242
[0.00103106 0.90921425 0.36346994] 0.8266716226925992 0.36346993848772036
[-4.50189897e-04  9.12072724e-01  3.61117428e-01] 0.8318768569591254 0.36111742773107836
[0.00330013 0.90768306 0.36171022] 0.8238994308216179 0.3617102153993647
[5.22578060e-04 9.03947690e-01 3.65883479e-01] 0.8171216992845143 0.365883479

[-0.07051554  0.98282126  0.39891442] 0.9709100630337917 0.39891441964807506
[-0.06728427  0.97863154  0.40383869] 0.9622468665513906 0.4038386892951301
[-0.06334435  0.97398155  0.40138785] 0.9526525661901403 0.4013878486780202
[-0.06388357  0.97467205  0.40047982] 0.9540667082276847 0.4004798178045837
[-0.06409082  0.97312269  0.40005275] 0.9510754115931341 0.40005275460073286
[-0.06684934  0.97595188  0.39852608] 0.9569509049515795 0.39852608041073523
[-0.07066318  0.97435621  0.39965626] 0.9543633157525753 0.3996562575872764
[-0.06977324  0.97585371  0.39530603] 0.957158766349738 0.39530603175821477
[-0.07078066  0.97732784  0.40003178] 0.9601796083072142 0.40003178400662726
[-0.06801751  0.97545767  0.40498497] 0.9561440425846941 0.404984973214946
[-0.07012159  0.97907495  0.40720227] 0.963504796478557 0.4072022710707383
[-0.06970234  0.97708115  0.40770786] 0.9595459801559033 0.40770786021016275
[-0.06769991  0.98126386  0.41057707] 0.9674620503292579 0.41057707347784683
[-0.0718

[-0.11686746  0.93323785  0.47518149] 0.8845908911436965 0.47518149383592057
[-0.1119763   0.93399534  0.47273596] 0.8848859881864555 0.4727359637854461
[-0.10877787  0.93436707  0.47675195] 0.8848744454082464 0.47675195132276943
[-0.11131189  0.93054769  0.47372602] 0.8783093345730715 0.47372602240558986
[-0.11405003  0.92670377  0.47253365] 0.8717872825833443 0.4725336545208261
[-0.11361265  0.92595606  0.46938926] 0.8703024624676294 0.46938925615601346
[-0.11821329  0.92684865  0.47340697] 0.8730228002575023 0.4734069674601871
[-0.12281885  0.93074373  0.46907793] 0.8813683629189718 0.46907793326492847
[-0.12685193  0.92799547  0.46888439] 0.8772669957956843 0.46888438741586086
[-0.13025232  0.92854814  0.46422065] 0.8791673138829206 0.4642206457938109
[-0.13302823  0.9287739   0.46354189] 0.8803174714583504 0.463541889533975
[-0.13677054  0.92403589  0.46158201] 0.8725485061891162 0.46158201442656244
[-0.13864028  0.92053019  0.46087778] 0.8665969552205832 0.4608777809895315
[-0.13

[-0.16212659  1.00713275  0.39659921] 1.0406014061979605 0.3965992135527575
[-0.15980902  1.00422566  0.39917595] 1.0340081028173116 0.39917594963996633
[-0.15830813  1.00744072  0.39592679] 1.039998270494012 0.3959267935983889
[-0.16119335  1.00661947  0.39247178] 1.0392660605169108 0.39247177708692776
[-0.16483922  1.00778121  0.39165794] 1.042794944008884 0.39165793981855024
[-0.16066277  1.00379846  0.38735827] 1.033423872147386 0.3873582665446578
[-0.16258568  0.99918949  0.38400441] 1.024813736280312 0.3840044086216344
[-0.1652227   0.99719448  0.38108137] 1.0216953670148812 0.3810813706761282
[-0.16819034  0.99343442  0.3831887 ] 1.0151999446378608 0.38318870038100716
[-0.17202659  0.99751225  0.38383694] 1.0246238347519627 0.38383694377835886
[-0.16841853  0.99653912  0.38453582] 1.021455010599218 0.38453581654121427
[-0.16654196  0.99737295  0.3825215 ] 1.0224890252919459 0.3825215005374376
[-0.16694708  0.99730162  0.38627536] 1.0224818486642924 0.38627536490898895
[-0.162622

KeyboardInterrupt: 

In [ ]:
ps = np.concatenate(positions, axis=0)
r  = np.sqrt(ps[:, 0]**2 + ps[:, 1]**2)
z  = ps[:, 2]
w  = np.array(weights)

In [ ]:
bins = (np.linspace(0, RMAX, 101), np.linspace(-ZMAX, ZMAX, 101))
plt.hist2d(r, z, bins)
plt.xlabel("R")
plt.ylabel("Z")
